{
 "title": "PostgreSQL connection exporter",
 "time": { "from": "2023-12-12T12:19:44.885Z", "to": "2023-12-12T12:59:44.885Z" },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM pg_stat_activity WHERE state = 'active';"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT datname, usename, query, state\nFROM pg_stat_activity\nWHERE state IS NOT NULL\nLIMIT 40; "
    }
   ]
  },
  {
   "title": "All connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM pg_stat_activity;"
    }
   ]
  },
  {
   "title": "Max connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT setting::INT FROM pg_settings WHERE name=$$max_connections$$"
    }
   ]
  }
 ]
}